# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2 
  database: dslide
  pool: 5
  username: mysql
  password: <Leokmax789_Emily>
  socket: /var/run/mysql/mysqld.sock
  encoding: utf8
production:
  adapter: mysql2 
  database: pslide
  pool: 15
  username: mysql
  password: <Leokmax789_Emily>
  socket: /var/run/mysql/mysqld.sock
  encoding: utf8
