# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2 
  database: dslide
  pool: 5
  username: root
  password: xlw123
  socket: /run/mysqld/mysqld.sock
  encoding: utf8
production:
  adapter: mysql2 
  database: dslide
  pool: 5
  username: root
  password: xlw123
  socket: /run/mysqld/mysqld.sock
  encoding: utf8
